import { describe, expect, it } from 'vitest';
import {
  decryptSessionKey,
  decryptWithPrivateKey,
  generateHandshakeKeyPair,
  importPrivateKeyPem,
} from '../src/crypto/rsa.js';
import { fromBase64, toBase64 } from '../src/crypto/bytes.js';

/**
 * The key pair below was generated by Web Crypto, and the ciphertext by the framework's
 * `RsaCryptor.EncryptWithPublicKey` using the matching public key PEM.
 *
 * That makes this one vector prove both directions at once: .NET accepted a SubjectPublicKeyInfo
 * PEM produced here (otherwise it could not have encrypted anything), and this package decrypts
 * what .NET produced. RSA-OAEP with a mismatched hash fails at neither end until decryption, so a
 * round-trip within one language would prove nothing about the pair of them.
 */
const PRIVATE_KEY_PEM = `
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIwy3qjn3Mm5LS
  fB4+BQtRDdUEn3hzUc9hzGPzyGnOz+f16wQqf8rxu7AoFM+4wUIgK4FIkQl60zIP
  KOVm4CMs3DQn6adp2Peou+n7tNWqoF+vS9UvR+Tnt/MkuZllm0f8/6QBKQVtLPPw
  18D2xujs8+DJFlrNLBfsCNArhEMTbI0LaJfubTFhwa8FMTKlPjdReajT14Px0T8d
  3qWdKqPKoDqcxMk+WuZeum9YRvQZoRySoZURtaCVHrvfLY2Tvsd4G3XoHi6JB8ce
  ZPcBgJMxkRjrZcv+PZlgIC8t9oWetyYysQSKO+cghXa86lbCpkrwmAI1wwsOb8HW
  LGPBThnnAgMBAAECggEAOxAUw5M9FkNUrADg4s0YGbXwi+YgiQix8qsvYqp82l+W
  9eW4uYoUGg7mEbyhqdCNVCqIY+FrgQt+CDC3YI8jOhDkdTOL0ZuHrMfv2+HFFGgP
  DmLIapsDkFoxOYYyx04qHRfWV5MKaiaV8659sfwtzXwoDvC5MPA+b23eVFcaZq18
  pyf/q3GUHmuaFe+kRHg2HlIso1lrqyGCkOg/30HZL9gTpqs9UTYI61UfzVgyTNnn
  0xyuz2PDxexFDej0aZWpqbkyUg9Umlz5Rzumt1QOgE4dM31xIUf8+zxCsXqO73Nk
  RjNqylD3Rx5qcQhW0bOqxv55okQogFnPc6GAvsuE7QKBgQDwg8KvRLxpEc5KIf2H
  G90V/RkC3Bgjadwi2T/XbSd2uTPvYeIc1Il5XucRREtY+4kQoZwpitjAPDqpkMpx
  /X1FKKHu+xGa/YNC+vaAquCyMS5rKJFh6gc24H2btaROyZwqBRSgU7SNY7kQxWVQ
  B7++DsrVo5Xc9ZhviNWvELEmLQKBgQDVsDWWuHO3uM0xtU+rgjP/jQC81pX4bvrU
  mltOAUCPNshqE9E/Klbq7SuCbRNzYHrB0ZYRY/K8YdboMZZ31vGUseQAA84W6WBd
  qDBsTPzq8sSHRjykdurCInZlRGbyynqbmhLXdBE5fCPpHG2FKNHlrlBgKjBG339T
  jsBwACZA4wKBgAL3HOdcSZZiCdEQKjgIN+mVfUFzxThqjbRASXE2f04PanyBEHCa
  jjdY3DByTxuBvmbeFzbL53A3TeHZTyWoomq/3X88yTLH/V5OCcv8T1jjEldv4Jr8
  b6pVijbpPmVaRvqdpWt0nL1BhX6XcHBUKCEHvah0o9xdisuVPE00P3rhAoGBAL54
  QkwGPZ8ValFUe580f4TZ+j5YR3UZ9xpqO9hb5V/CRQHIiEr1QmRE4vNuplfBN6pr
  VohJvqOL0jNFgAlx3gPcTI521cw2WV8h+4eNWCNUITkysfsmxDom3cGGJv1i3ca0
  nvbMzk2fCaNPY4+9wtondh1BfaausJ+aLo2mlHJhAoGBANuhud05ksz/g0eMM+nc
  TxoqOcl/grG9llq0TBgYTtYfNfgHfvWEGo51SnWMEvFs06NOeFw1qknDGnZVHjrv
  YOD2Mdfjgog/khlUj+D+YB7rvGPoBtoH+ycVYU5XiRh2d3COj3g97uxMf9+J6cfO
  8c7BkvOPrm/tS69k3+DARfpF
  -----END PRIVATE KEY-----
`.trim();

/** The 64-byte combined session key the server wrapped, as its Base64 text. */
const SESSION_KEY_BASE64 = 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+Pw==';

/** Produced by .NET with the public half of the key above. */
const CIPHER_FROM_DOTNET_BASE64 = 'N6YBybw4TNqFH93z0+flOvD/sNYVwk/IqbCIlfJVr+ER5bErxhNw4yCR10dnh8lVN3d+PModYR/fDknk7JpONNg8p70ocv/mHmRbEluD5l11cVm7H4VBqVv6wUd1zngB8MQCQNaka2hRFTG1tO0fr0/vW6ogGr1fsvHZA+2/WdNfWDVDGFLFCpDsL4MmLURo8j7eCB1WDlITTwm2pEUorFho1UJ4nFZvENkfkqBOdajO44AImS9WkZ+fVwrbleXvCpHjFmHg5bwCR4hPYHy+aqojnwl336Dv/OFZeRBSNIZlCNgr9Ck4QjijAgb26RvsK98qdmE4rp7M89vv1lGetA==';

/** The public half of PRIVATE_KEY_PEM, used only by the negative test above. */
const PUBLIC_FOR_NEGATIVE = `
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyMMt6o59zJuS0nwePgUL
  UQ3VBJ94c1HPYcxj88hpzs/n9esEKn/K8buwKBTPuMFCICuBSJEJetMyDyjlZuAj
  LNw0J+mnadj3qLvp+7TVqqBfr0vVL0fk57fzJLmZZZtH/P+kASkFbSzz8NfA9sbo
  7PPgyRZazSwX7AjQK4RDE2yNC2iX7m0xYcGvBTEypT43UXmo09eD8dE/Hd6lnSqj
  yqA6nMTJPlrmXrpvWEb0GaEckqGVEbWglR673y2Nk77HeBt16B4uiQfHHmT3AYCT
  MZEY62XL/j2ZYCAvLfaFnrcmMrEEijvnIIV2vOpWwqZK8JgCNcMLDm/B1ixjwU4Z
  5wIDAQAB
  -----END PUBLIC KEY-----
`.trim();


describe('RSA handshake', () => {
  it('decrypts a session key wrapped by the .NET implementation', async () => {
    const privateKey = await importPrivateKeyPem(PRIVATE_KEY_PEM);

    const key = await decryptSessionKey(CIPHER_FROM_DOTNET_BASE64, privateKey);

    expect(key.length).toBe(64);
    expect(toBase64(key)).toBe(SESSION_KEY_BASE64);
    // The framework hands out a combined key whose halves are the AES and HMAC keys.
    expect(Array.from(key.subarray(0, 4))).toEqual([0, 1, 2, 3]);
  });

  it('reads the ciphertext as UTF-8 text, not as raw key bytes', async () => {
    const privateKey = await importPrivateKeyPem(PRIVATE_KEY_PEM);

    // The value inside the envelope is Base64 *text*; treating it as the key directly would yield
    // 88 bytes instead of 64, which is exactly the mistake this asserts against.
    const text = await decryptWithPrivateKey(CIPHER_FROM_DOTNET_BASE64, privateKey);
    expect(text).toBe(SESSION_KEY_BASE64);
    expect(fromBase64(text).length).toBe(64);
  });

  it('exports a public key PEM in the form the server can import', async () => {
    const { publicKeyPem } = await generateHandshakeKeyPair();

    expect(publicKeyPem.startsWith('-----BEGIN PUBLIC KEY-----\n')).toBe(true);
    expect(publicKeyPem.trimEnd().endsWith('-----END PUBLIC KEY-----')).toBe(true);

    const body = publicKeyPem
      .replace(/-----[A-Z ]+-----/g, '')
      .trim();
    // PEM wraps at 64 characters; a single long line is accepted by some readers and not others.
    for (const line of body.split('\n')) {
      expect(line.length).toBeLessThanOrEqual(64);
    }
    expect(fromBase64(body.replace(/\s+/g, '')).length).toBeGreaterThan(200);
  });

  it('keeps the private key non-extractable', async () => {
    const { privateKey } = await generateHandshakeKeyPair();

    expect(privateKey.extractable).toBe(false);
    await expect(crypto.subtle.exportKey('pkcs8', privateKey)).rejects.toThrow();
  });

  it('rejects a wrapped value that is not a 64-byte key', async () => {
    const privateKey = await importPrivateKeyPem(PRIVATE_KEY_PEM);

    // Encrypt a short string with the matching public key so decryption succeeds but the
    // unwrapped key is the wrong size.
    const spki = fromBase64(
      PUBLIC_FOR_NEGATIVE.replace(/-----[A-Z ]+-----/g, '').replace(/\s+/g, ''),
    );
    const pub = await crypto.subtle.importKey(
      'spki',
      spki,
      { name: 'RSA-OAEP', hash: 'SHA-256' },
      false,
      ['encrypt'],
    );
    const cipher = new Uint8Array(
      await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, pub, new TextEncoder().encode('c2hvcnQ=')),
    );

    await expect(decryptSessionKey(toBase64(cipher), privateKey)).rejects.toThrow(/64 bytes/);
  });
});
