// Synced from polhem-dev/polhem/wire-contracts/type-names.ts — do not edit by hand.
// Update with `npm run contracts:update`; CI fails if this file drifts from the source.

// Generated from the Polhem message types — do not edit by hand.
//
// An encoded payload must name its type in the envelope; the server resolves it from this
// string and screens it against an allow-list first.

export const WireTypeNames = {
  AuditLogAggregateResponse: 'Polhem.Api.Core.Messages.AuditLog.AuditLogAggregateResponse, Polhem.Api.Core',
  AuditLogListResponse: 'Polhem.Api.Core.Messages.AuditLog.AuditLogListResponse, Polhem.Api.Core',
  CreateApiKeyRequest: 'Polhem.Api.Core.Messages.System.CreateApiKeyRequest, Polhem.Api.Core',
  CreateApiKeyResponse: 'Polhem.Api.Core.Messages.System.CreateApiKeyResponse, Polhem.Api.Core',
  CreateSessionRequest: 'Polhem.Api.Core.Messages.System.CreateSessionRequest, Polhem.Api.Core',
  CreateSessionResponse: 'Polhem.Api.Core.Messages.System.CreateSessionResponse, Polhem.Api.Core',
  DeleteRequest: 'Polhem.Api.Core.Messages.Form.DeleteRequest, Polhem.Api.Core',
  DeleteResponse: 'Polhem.Api.Core.Messages.Form.DeleteResponse, Polhem.Api.Core',
  EnterCompanyRequest: 'Polhem.Api.Core.Messages.System.EnterCompanyRequest, Polhem.Api.Core',
  EnterCompanyResponse: 'Polhem.Api.Core.Messages.System.EnterCompanyResponse, Polhem.Api.Core',
  ExecFuncRequest: 'Polhem.Api.Core.Messages.ExecFuncRequest, Polhem.Api.Core',
  ExecFuncResponse: 'Polhem.Api.Core.Messages.ExecFuncResponse, Polhem.Api.Core',
  GetAccessLogRequest: 'Polhem.Api.Core.Messages.AuditLog.GetAccessLogRequest, Polhem.Api.Core',
  GetApiAnomalyLogRequest: 'Polhem.Api.Core.Messages.AuditLog.GetApiAnomalyLogRequest, Polhem.Api.Core',
  GetApiAnomalySummaryRequest: 'Polhem.Api.Core.Messages.AuditLog.GetApiAnomalySummaryRequest, Polhem.Api.Core',
  GetChangeDetailRequest: 'Polhem.Api.Core.Messages.AuditLog.GetChangeDetailRequest, Polhem.Api.Core',
  GetChangeDetailResponse: 'Polhem.Api.Core.Messages.AuditLog.GetChangeDetailResponse, Polhem.Api.Core',
  GetChangeLogRequest: 'Polhem.Api.Core.Messages.AuditLog.GetChangeLogRequest, Polhem.Api.Core',
  GetCommonConfigurationRequest: 'Polhem.Api.Core.Messages.System.GetCommonConfigurationRequest, Polhem.Api.Core',
  GetCommonConfigurationResponse: 'Polhem.Api.Core.Messages.System.GetCommonConfigurationResponse, Polhem.Api.Core',
  GetCustomizePluginSettingsRequest: 'Polhem.Api.Core.Messages.System.GetCustomizePluginSettingsRequest, Polhem.Api.Core',
  GetCustomizePluginSettingsResponse: 'Polhem.Api.Core.Messages.System.GetCustomizePluginSettingsResponse, Polhem.Api.Core',
  GetDataRequest: 'Polhem.Api.Core.Messages.Form.GetDataRequest, Polhem.Api.Core',
  GetDataResponse: 'Polhem.Api.Core.Messages.Form.GetDataResponse, Polhem.Api.Core',
  GetDbAnomalyLogRequest: 'Polhem.Api.Core.Messages.AuditLog.GetDbAnomalyLogRequest, Polhem.Api.Core',
  GetDbAnomalySummaryRequest: 'Polhem.Api.Core.Messages.AuditLog.GetDbAnomalySummaryRequest, Polhem.Api.Core',
  GetDefineRequest: 'Polhem.Api.Core.Messages.System.GetDefineRequest, Polhem.Api.Core',
  GetDefineResponse: 'Polhem.Api.Core.Messages.System.GetDefineResponse, Polhem.Api.Core',
  GetDepartmentTreeRequest: 'Polhem.Api.Core.Messages.System.GetDepartmentTreeRequest, Polhem.Api.Core',
  GetDepartmentTreeResponse: 'Polhem.Api.Core.Messages.System.GetDepartmentTreeResponse, Polhem.Api.Core',
  GetFormLayoutRequest: 'Polhem.Api.Core.Messages.System.GetFormLayoutRequest, Polhem.Api.Core',
  GetFormLayoutResponse: 'Polhem.Api.Core.Messages.System.GetFormLayoutResponse, Polhem.Api.Core',
  GetFormSchemaRequest: 'Polhem.Api.Core.Messages.System.GetFormSchemaRequest, Polhem.Api.Core',
  GetFormSchemaResponse: 'Polhem.Api.Core.Messages.System.GetFormSchemaResponse, Polhem.Api.Core',
  GetLanguageRequest: 'Polhem.Api.Core.Messages.System.GetLanguageRequest, Polhem.Api.Core',
  GetLanguageResponse: 'Polhem.Api.Core.Messages.System.GetLanguageResponse, Polhem.Api.Core',
  GetListRequest: 'Polhem.Api.Core.Messages.Form.GetListRequest, Polhem.Api.Core',
  GetListResponse: 'Polhem.Api.Core.Messages.Form.GetListResponse, Polhem.Api.Core',
  GetLoginLogRequest: 'Polhem.Api.Core.Messages.AuditLog.GetLoginLogRequest, Polhem.Api.Core',
  GetLookupRequest: 'Polhem.Api.Core.Messages.Form.GetLookupRequest, Polhem.Api.Core',
  GetLookupResponse: 'Polhem.Api.Core.Messages.Form.GetLookupResponse, Polhem.Api.Core',
  GetNewDataRequest: 'Polhem.Api.Core.Messages.Form.GetNewDataRequest, Polhem.Api.Core',
  GetNewDataResponse: 'Polhem.Api.Core.Messages.Form.GetNewDataResponse, Polhem.Api.Core',
  GetTopApiMethodsRequest: 'Polhem.Api.Core.Messages.AuditLog.GetTopApiMethodsRequest, Polhem.Api.Core',
  LeaveCompanyRequest: 'Polhem.Api.Core.Messages.System.LeaveCompanyRequest, Polhem.Api.Core',
  LeaveCompanyResponse: 'Polhem.Api.Core.Messages.System.LeaveCompanyResponse, Polhem.Api.Core',
  ListApiKeysRequest: 'Polhem.Api.Core.Messages.System.ListApiKeysRequest, Polhem.Api.Core',
  ListApiKeysResponse: 'Polhem.Api.Core.Messages.System.ListApiKeysResponse, Polhem.Api.Core',
  LoginRequest: 'Polhem.Api.Core.Messages.System.LoginRequest, Polhem.Api.Core',
  LoginResponse: 'Polhem.Api.Core.Messages.System.LoginResponse, Polhem.Api.Core',
  LogoutRequest: 'Polhem.Api.Core.Messages.System.LogoutRequest, Polhem.Api.Core',
  LogoutResponse: 'Polhem.Api.Core.Messages.System.LogoutResponse, Polhem.Api.Core',
  PingRequest: 'Polhem.Api.Core.Messages.System.PingRequest, Polhem.Api.Core',
  PingResponse: 'Polhem.Api.Core.Messages.System.PingResponse, Polhem.Api.Core',
  SaveCustomizePluginSettingsRequest: 'Polhem.Api.Core.Messages.System.SaveCustomizePluginSettingsRequest, Polhem.Api.Core',
  SaveCustomizePluginSettingsResponse: 'Polhem.Api.Core.Messages.System.SaveCustomizePluginSettingsResponse, Polhem.Api.Core',
  SaveDefineRequest: 'Polhem.Api.Core.Messages.System.SaveDefineRequest, Polhem.Api.Core',
  SaveDefineResponse: 'Polhem.Api.Core.Messages.System.SaveDefineResponse, Polhem.Api.Core',
  SaveRequest: 'Polhem.Api.Core.Messages.Form.SaveRequest, Polhem.Api.Core',
  SaveResponse: 'Polhem.Api.Core.Messages.Form.SaveResponse, Polhem.Api.Core',
  SetApiKeyEnabledRequest: 'Polhem.Api.Core.Messages.System.SetApiKeyEnabledRequest, Polhem.Api.Core',
  SetApiKeyEnabledResponse: 'Polhem.Api.Core.Messages.System.SetApiKeyEnabledResponse, Polhem.Api.Core',
  SetApiKeyExpiryRequest: 'Polhem.Api.Core.Messages.System.SetApiKeyExpiryRequest, Polhem.Api.Core',
  SetApiKeyExpiryResponse: 'Polhem.Api.Core.Messages.System.SetApiKeyExpiryResponse, Polhem.Api.Core',
  SetDeploymentAdminRequest: 'Polhem.Api.Core.Messages.System.SetDeploymentAdminRequest, Polhem.Api.Core',
  SetDeploymentAdminResponse: 'Polhem.Api.Core.Messages.System.SetDeploymentAdminResponse, Polhem.Api.Core',
} as const;

export type WireTypeName = keyof typeof WireTypeNames;
